management.security.enabled: false
security.basic.enabled: false

dbhost: 127.0.0.1
dbport: 11301

server:
  port: 9090
  contextPath: /retail

spring:
  profile: dev
  cloud:
    discovery:
      enabled: false
  datasource:
    url: jdbc:mysql://${dbhost}:${dbport}/sspms?autoReconnect=true&tinyInt1isBit=false&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 'tenxdev'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

